LibrarySLN/LibraryUI/Areas/Admin/Controllers/DashboardController.cs
using System.Web.Mvc;

namespace LibraryUI.Areas.Admin.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Admin/Dashboard
        public ActionResult Index()
        {
            return View();
        }

        // GET: Admin/Dashboard/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/Dashboard/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Dashboard/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Dashboard/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Admin/Dashboard/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Dashboard/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Admin/Dashboard/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

LibrarySLN/LibraryUI/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top myMenu">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Library", "Index", "Home", new { area = "" }, new { @class = "navbar-brand menuItem" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        @Html.ActionLink("Reader", "Index", "Home",
                       new { area = "" }, htmlAttributes: new { id = "readerLink" })
                    </li>
                    <li>
                        @Html.ActionLink("Librarian", "Index", "Dashboard",
                        new { area = "Admin" }, htmlAttributes: new { id = "activeLink" })
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2 adminDashboard">
                <ul id="menuActiveAdmin">
                    <li class="dashboard">@Html.ActionLink("BookCards", "Index", "BookCards")</li>
                    <li class="dashboard">@Html.ActionLink("Authors", "Index", "Authors")</li>
                    <li class="dashboard">@Html.ActionLink("Users", "Index", "Users")</li>
                    <li class="dashboard">@Html.ActionLink("Orders", "Index", "Orders")</li>
                </ul>
            </div>

            <div class="col-md-9 mainContent">
                @RenderBody()
            </div>
        </div>
    </div>
    
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>